### ISSUE TITLE
Reformat igel -h output

### ISSUE THREAD

**Issue by dinhanhx** [nidhaloff/igel#19]
As the title, I think `igel -h` should print less than 80 characters per line. As a result, the users can read more easily.

![image](https://user-images.githubusercontent.com/38489776/94409688-ba7bc200-01a0-11eb-93fc-eb9d157f722d.png)
 I have to use the terminal at maximized state to read the page.

**Comment by dinhanhx** [comment]
I am working on this.. because it's easy to do first

**Comment by nidhaloff** [comment]
@dinhanhx Alright ;)

**Comment by dinhanhx** [comment]
@nidhaloff may I use [colorama](https://github.com/tartley/colorama) to support colored text?

**Comment by nidhaloff** [comment]
@dinhanhx If you think that it will bring a huge impact or great improvements (readablity etc..) then you may use it. However, I generally prefer not to add dependencies that are unecessary. Like if I'm going to use only one small function from the package then I will rather write it myself. 

So, it's up to what you want to improve and how good will it be if you used the package vs if you don't. You can use it and compare for yourself later if this is something that users will fall in love to or if it is actually not needed and will not bring a great impact.

**Comment by nidhaloff** [comment]
@dinhanhx did you get what I mean or did it confused you? sorry if it wasn't clear! what I meant is, I see a lot of developers (including myself in the past) using some library, where they only need one little function from. So they download Idk how many megabytes in order to use a simple function. That's redundant. Hence, what I want to say is, if you think that using colorama will bring good improvements then go ahead and do it, else if it's not really imprtant than it would be better not to use it, right`?

**Comment by dinhanhx** [comment]
@nidhaloff  I got what you meant. I just used "look emoji" to express that I have looked and will think about this. I am surely going to use colorama to color text in all platforms.

**Comment by dinhanhx** [comment]
Please link this with #29
