### ISSUE TITLE
Latest release / Python Packages on PyPi

### ISSUE THREAD

**Issue by ondics** [nidhaloff/igel#39]
What is the latest release of this repo?

The current release here on Github is 0.2.3: https://github.com/nidhaloff/igel/releases
The latest release on PyPi is 0.2.7: https://pypi.org/project/igel/#history

Please sync the releases.

Thanx.

**Comment by dinhanhx** [comment]
It's the one on PyPi.

**Comment by nidhaloff** [comment]
@ondics You can find all changes log (release history) in the pypi website[ here](https://pypi.org/project/igel/)

I update the history on github now. However, I'm not a fan of updating release versions manually on github, since I automated this and already synced with pypi. Therefore, check on pypi whenever you want to see the latest release & the release history
