### ISSUE TITLE
Docs need different path to images

### ISSUE THREAD

**Issue by evelynmitchell** [nidhaloff/igel#41]
https://igel.readthedocs.io/en/latest/_sources/readme.rst.txt includes a link to the assets/igel-help.gif, but that path is broken on readthedocs. 

readme.rst is included as ../readme.rst in the sphinx build.
The gifs are in asses/igel-help.gif

The sphinx build needs to point to the asset directory, absolutely:

.. image:: /assets/igel-help.gif

I haven't made a patch, because I haven't tested this.

**Comment by nidhaloff** [comment]
@evelynmitchell Thanks for opening this. Yes you are right I checked it now, I don't have much time these days that's why I didn't notice this. I will try to check it out when I have more time. Feel free to work on solving this if you would like to, or maybe someone else can investigate this meanwhile.
