### ISSUE TITLE
Is there any function to support me to export Python code after igel training?

### ISSUE THREAD

**Issue by 935462955** [nidhaloff/igel#50]

**Comment by nidhaloff** [comment]
Hi @935462955 No there is no function for this at the moment. Can you provide why would this be useful for you?

**Comment by 935462955** [comment]
Thanks for your reply! I am a novice machine learning, but I want to apply the model that trained on igxl to my project. I think that maybe I can learn machine learning knowledge through the exported code and save development time.

**Comment by nidhaloff** [comment]
@935462955 You can certainly apply the trained model with igel to your project! The model will be saved for you in the model_results folder after training/fitting. You can load it with python and use it as you wish.

Unfortunately, the code will not be shipped with it since everything is created **dynamically in the background**. Furthermore, learning machine learning with igel is probably a bad idea, since **everything is abstracted for you** so that you don't need to worry about a thing when you are using ML, so I would suggest that you try different approaches if you are willing to dive into the details and **learn ML**. Igel is for **lazy** (like me) professionals/developers who already know ML and wants to use it in a more organized manner or for completely non-technical users that have no interest in knowing what's happening in the background.
